#!/bin/bash
# Provision the CLIENT (LEFT) VM.
# Env vars from Vagrantfile: PEER_IP (gateway's underlay IP)
set -euo pipefail

PEER_IP="${PEER_IP:-192.168.100.1}"
KEYS_DIR="/vagrant/vagrant/keys"
DAEMON="/vagrant/userspace/wg-zk-daemon/target/release/wg-zk-daemon"

mkdir -p "$KEYS_DIR"

# ── WireGuard keys ────────────────────────────────────────────────────────────
WG_PRIV="/etc/wireguard/private_left"
WG_PUB="$KEYS_DIR/publeft"
umask 077
mkdir -p /etc/wireguard
wg genkey > "$WG_PRIV"
wg pubkey < "$WG_PRIV" > "$WG_PUB"
echo "==> WireGuard public key (client): $(cat $WG_PUB)"

# ── ZK keys (generated by gateway) ────────────────────────────────────────────
ZK_ENV="$KEYS_DIR/zk.env"
echo "==> Waiting for ZK keys at $ZK_ENV ..."
for i in $(seq 1 60); do
    [ -f "$ZK_ENV" ] && break
    sleep 2
done
[ -f "$ZK_ENV" ] || { echo "ERROR: ZK keys not found after 120s (gateway not provisioned yet?)"; exit 1; }
source "$ZK_ENV"

# ── WireGuard interface (wait for gateway pubkey) ──────────────────────────────
echo "==> Waiting for gateway public key at $KEYS_DIR/pubright ..."
for i in $(seq 1 60); do
    [ -f "$KEYS_DIR/pubright" ] && break
    sleep 2
done
[ -f "$KEYS_DIR/pubright" ] || { echo "ERROR: gateway pubkey not found after 120s"; exit 1; }

ip link add wg1l type wireguard 2>/dev/null || true
ip addr add 192.168.1.1/32 dev wg1l 2>/dev/null || true
ip link set wg1l up
wg set wg1l private-key "$WG_PRIV" listen-port 51821
ip link set wg1l mtu 1380
wg set wg1l \
    peer "$(cat $KEYS_DIR/pubright)" \
    allowed-ips 10.20.10.0/24 \
    endpoint "${PEER_IP}:51921" \
    persistent-keepalive 5
ip route replace 10.20.10.0/24 dev wg1l

# ── Dummy interface ───────────────────────────────────────────────────────────
ip link add dum0l type dummy 2>/dev/null || true
ip addr add 10.10.10.10/24 dev dum0l 2>/dev/null || true
ip link set dum0l up

# ── rp_filter ─────────────────────────────────────────────────────────────────
sysctl -w net.ipv4.conf.all.rp_filter=0 >/dev/null
sysctl -w net.ipv4.conf.wg1l.rp_filter=0 >/dev/null || true
sysctl -w net.ipv4.conf.dum0l.rp_filter=0 >/dev/null || true

# ── Daemon ────────────────────────────────────────────────────────────────────
if [ ! -f "$DAEMON" ]; then
    echo "ERROR: $DAEMON not found. Build it: cd userspace/wg-zk-daemon && cargo build --release"
    exit 1
fi
chmod +x "$DAEMON"
cat > /etc/wgzk-client.env <<EOF
WGZK_MODE=client
WGZK_SK_HEX=${WGZK_SK_HEX}
WGZK_PK_HEX=${WGZK_PK_HEX}
EOF

cat > /etc/systemd/system/wgzk.service <<EOF
[Unit]
Description=WireGuard ZK Daemon (client)
After=network.target

[Service]
EnvironmentFile=/etc/wgzk-client.env
ExecStart=${DAEMON}
Restart=on-failure
RestartSec=1

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable wgzk
systemctl start wgzk
sleep 2
systemctl is-active wgzk && echo "==> wgzk daemon running (client)" || {
    journalctl -u wgzk --no-pager -n 20
    exit 1
}

echo "==> Client provisioning complete"
wg show wg1l
